name: Push to Registry

on:
  release:
    types: [published]

env:
  IMAGE_NAME: cardinal4/conda-mvn
  PATH_CONTEXT: miniconda2-temurin

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ IMAGE_NAME }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${PATH_CONTEXT}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ IMAGE_NAME }}
