name: Push to Registry

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  IMAGE_NAME: cardinal4/conda-mvn

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}

      - name: Build & Push Miniconda to Docker Hub
        run: |
          ./miniconda-temurin8-3/build.sh
          ./miniconda-temurin11-3/build.sh
          ./miniconda-temurin17-3/build.sh
          
      - name: Build & Push Miniconda2 to Docker Hub
        run: |
          ./miniconda2-temurin8-3/build.sh
          ./miniconda2-temurin11-3/build.sh
          ./miniconda2-temurin17-3/build.sh
          
      - name: Build & Push Miniconda3 to Docker Hub
        run: |
          ./miniconda3-temurin8-3/build.sh
          ./miniconda3-temurin11-3/build.sh
          ./miniconda3-temurin17-3/build.sh

      - name: Build & Push Miniforge3 to Docker Hub
        run: |
          ./miniforge3-temurin8-3/build.sh
          ./miniforge3-temurin11-3/build.sh
          ./miniforge3-temurin17-3/build.sh
